### ISSUE TITLE
app() global helper function

### ISSUE THREAD

**Issue by MrKarlDilkington** [shahroq/whale_c5_cheat_sheet#13]
Starting with concrete5 8.5.2, there is a new global `app()` helper function.
https://github.com/concrete5/concrete5/pull/8011

I am not entirely sure what the cheat sheet text should be. I imagine @mlocati might have an opinion on it.

**Comment by mlocati** [comment]
What about #14 ?

**Comment by MrKarlDilkington** [comment]
That is great, thank you.
