### ISSUE TITLE
Japanese branch

### ISSUE THREAD

**Issue by tao-s** [shahroq/whale_c5_cheat_sheet#18]
Thank you for great cheat sheet.
I started to translate [Japanese version](https://github.com/tao-s/whale_c5_cheat_sheet/tree/japanese).

Would you add Japanese branch?
I want to send PR to Japanese branch, not master.

**Comment by shahroq** [comment]
@tao-s 
Hi Tao,
Done.

**Comment by tao-s** [comment]
@shahroq Thank you!
