### ISSUE TITLE
Moving this repository to concrete5-community?

### ISSUE THREAD

**Issue by mlocati** [shahroq/whale_c5_cheat_sheet#19]
This repository is so useful that it deserves more visibility.

So, what about moving it under the https://github.com/concrete5-community umbrella?
- You can do that very easily (see https://concrete5.slack.com/archives/C2N3FLUBW/p1576244900002700)
- GitHub will automatically redirect all web/git calls from https://github.com/shahroq/whale_c5_cheat_sheet to the moved repository
- You will still be the administrator of the repository
- Every issue/pull request/... will be moved too

So, I don't see any issue...

**Comment by MrKarlDilkington** [comment]
I am in total agreement with mlocati. This is a great repo and more people need to see it.

**Comment by shahroq** [comment]
@mlocati OK, I will take a look at it.
Cheers,
