### ISSUE TITLE
Logging to a new channel

### ISSUE THREAD

**Issue by dbuonomo** [shahroq/whale_c5_cheat_sheet#21]
Logging to a new channel. This works for any of the levels - e.g. addNotice, addAlert, etc.

use Concrete\Core\Logging\LoggerFactory;

$logger = $this->app->make(LoggerFactory::class)->createLogger('your_new_channel');
$logger->addNotice('A notice level  log message.');
$logger->addInfo('A info level log message.');

**Comment by shahroq** [comment]
ThanX. I added an entry for this.
