### ISSUE TITLE
Change  $page->isSystemPage() for $page->isAdminArea()

### ISSUE THREAD

**Issue by linuxoid** [shahroq/whale_c5_cheat_sheet#25]
I guess `$page->isSystemPage()` was meant to show if the page is a Dashboard page, and if so, it's not actually what it is, it should be `$page->isAdminArea()`.

https://documentation.concrete5.org/api/8.5.2/Concrete/Core/Page/Page.html#method_isSystemPage
vs
https://documentation.concrete5.org/api/8.5.2/Concrete/Core/Page/Page.html#method_isAdminArea

**Comment by shahroq** [comment]
Thanks for the heads-up. `$page->isAdminArea()` is added: 0e34140
