### ISSUE TITLE
[suggestion] How about adding a section for v9 specific stuff?

### ISSUE THREAD

**Issue by linuxoid** [shahroq/whale_c5_cheat_sheet#26]
How about adding a section for v9 specific stuff? Only for what's different from v8 or new, e.g. Tasks etc..

For example:

https://forums.concretecms.org/t/v9-group-add-and-delete-deprecated-what-to-use-instead/1499
https://forums.concretecms.org/t/v8-to-v9-package-conversion-tabs/1414
https://forums.concretecms.org/t/v8-to-v9-package-conversion-how-to-get-user-ip-address/1406/2
https://forums.concretecms.org/t/v9-how-to-make-tooltips-work-in-block-edit-form/1389

**Comment by shahroq** [comment]
Sure @linuxoid . At one point I am going to create a new branch for V9.
