### ISSUE TITLE
[Documentation] Express Entity - Create the entity - User Selector

### ISSUE THREAD

**Issue by BloodyIron** [shahroq/whale_c5_cheat_sheet#32]
Hey so I don't have permissions to PR or whatever, so I'm just going to paste here something I found worth adding to the documentation as it is absent, but testing shows this works:

// user_selector
$eObj->addAttribute('user_selector', 'Which User', 'which_user');

**Comment by shahroq** [comment]
Thank you. I appreciate it if you fork and send a pull request on this.
