### ISSUE TITLE
[Documentation] Improvement - Express Entry - order

### ISSUE THREAD

**Issue by BloodyIron** [shahroq/whale_c5_cheat_sheet#33]
Hey so again, I don't have PR permissions or whatever, but just wanted to post something helpful.

In the section:

    // select
    $eObj->addAttribute('select', 'Facilities', 'marina_facilities', $settings);
    $settings = new \Concrete\Core\Entity\Attribute\Key\Settings\SelectSettings();
    $settings->setAllowMultipleValues(false);
    $settings->setDisplayMultipleValuesOnSelect(false);
    $settings->setHideNoneOption(false);
    $settings->setAllowOtherValues(false);
    $settings->setDisplayOrder('display_asc');

It seems to me that the "$eObj" line should be at the end, otherwise it will fail since the $settings variable will neither exist, nor have the desired parameters set for it. AFAIK order of operations matter in this regard.

Hope this helps!

**Comment by mlocati** [comment]
> I don't have PR permissions or whatever

Sure you have: simply go to https://github.com/shahroq/whale_c5_cheat_sheet/blob/master/README.md and click this icon: ![immagine](https://github.com/shahroq/whale_c5_cheat_sheet/assets/928116/cdbe38f8-24b7-4d11-bd99-813c8cb643d6)

**Comment by BloodyIron** [comment]
Oh well then maybe I'll just have to try that! Shows what I know ;P

**Comment by mlocati** [comment]
Everyone starts from the beginning 😉

**Comment by shahroq** [comment]
Here too. I appreciate it if you fork and send a pull request on this.
