### ISSUE TITLE
Documentation of Address Attribute (Formatting, elements)

### ISSUE THREAD

**Issue by cedric-ES** [shahroq/whale_c5_cheat_sheet#34]
Hello,

I think it would be nice to have some info about Address Formatting in the attribute section as this documentation is not easily accessible :

I found the answer here :
https://github.com/concretecms/concretecms/issues/7943#issuecomment-507694014

I think it is not really documented in Concrete Documentation.

The Address Attribute is a complex attribute often needed.
It has some elements like country that you can get with getCountry() or getFullCountry()
It also has a getDisplayValue() that provide localized HTML output and a toArray() that provide a localized text output
https://documentation.concretecms.org/api/9.2.8/Concrete/Core/Entity/Attribute/Value/Value/AddressValue.html

The Address Formater Service need an array, can output in 'html' or 'text' (optional, default html) and can also get a locale (optional).

**Comment by shahroq** [comment]
Thanks @cedric-ES  
Done
