### ISSUE TITLE
General attribute checkboxes when adding attributes

### ISSUE THREAD

**Issue by shahroq** [shahroq/whale_c5_cheat_sheet#7]
Could anyone complete updating the general checkboxes section here? 
(I marked it with "help wanted")
https://github.com/shahroq/whale_c5_cheat_sheet#create-the-entity
@mlocati

**Comment by mnakalay** [comment]
Hello. I'd like to help but I'm not sure I understand what you're trying to do. What do you mean by general checkbox section? I looked at what you already have but I'm a bit confused.

Can you say more about what should be in that section?

**Comment by shahroq** [comment]
@mnakalay Hi Nour, I really appreciate you getting involved in completing this document. By general checkboxes, I mean these 2 fields which exist in all attribute field types:

![general-checkboxes](https://user-images.githubusercontent.com/7886999/60629754-39524580-9e0c-11e9-9af2-4beec56386d6.jpg)

I guess the overall purpose of the code should be obvious. It creates an express entity, and add one field of each type to the entity. The comments in the "help wanted" section (my drafted notes when working on this and off course confusing!) indicate the methods I guessed are responsible for updating these two checkboxes, but I couldn't make them work.

**Comment by mnakalay** [comment]
I looked into this and I couldn't find any elegant way to do it. It seems the core team only planned on setting those two when doing it from the dashboard. An oversight maybe.

So anyway, I do have a way (still needs testing) which happens after all attributes are added. Like I said, not elegant at all. 

I'll test it and post it and you can decide whether you want to add it to the list or not.
