### ISSUE TITLE
Superglobals section

### ISSUE THREAD

**Issue by mnakalay** [shahroq/whale_c5_cheat_sheet#9]
In the superglobal section, the get() function also takes a second parameter to serve as a fallback value if the key is not present. So

$request->request->get('key', 'some default value')

will return 'some default value' if $_POST['key'] doesn't exist

There are lots of other useful functions available like

- all() to get the whole array
- keys() to get an array of all the keys
- has() to check if a key exists

And many others

It's probably not a good idea to list them all but you could reference the file where those functions are available for people to check. It's vendor\symfony\http-foundation\ParameterBag.php

**Comment by shahroq** [comment]
Updated.
